### ISSUE TITLE
Version 1.1.13 - regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Bouhtouch** [factorial-io/undo-redo-vuex#10]
Hi there,
first of all thank you for this awesome plugin.

I just updated to the latest version (1.1.8 to 1.1.13) and unfortunately it breaks with "Uncaught ReferenceError: regeneratorRuntime is not defined" (from console log).

I downgraded to 1.1.12 and it seems it's working fine. Am I missing something new in the plugin's setup? I checked the documentation and it doesn't seem changed.

Cheers!

**Comment by andrewbeng89** [comment]
Hi @Bouhtouch thank you for the the heads-up on this bug: there was some issues with the bundling of Babel built-in helpers.

I believe this issue should be resolved with `v1.1.15`. Could you please test this version (`@latest`) and let me know if the issue still exists? 🙂

**Comment by Bouhtouch** [comment]
Hi @andrewbeng89, sorry for the late reply.
Yup it works like a charm.

Thank you again for the good job ;)

Cheers!
