### ISSUE TITLE
Feature enhancement: `reset` action should empty the undo/redo stacks, but maintain/rebase the current state of the store/module at this point.

### ISSUE THREAD

**Issue by andrewbeng89** [factorial-io/undo-redo-vuex#13]
This enhancement builds on from #7. The current `clear` action will empty the undo/redo stacks and set the state of the store when the `emptyState` mutation is committed. The _new_ `reset` action should empty the undo/redo stacks, but still maintain the state of the store up to this particular point.

**IS**
- given done: `[mutationA, mutationB]`, undone: `[mutationC]`, state: `emptyState + mutationA, mutationB`
- when `clear()` is dispatched
- then done: `[]`, undone: `[]`, state: `emptyState`

**SHOULD**
- [ ] given done: `[mutationA, mutationB]`, undone: `[mutationC]`, state: `emptyState + mutationA, mutationB`
- [ ] when `reset()` is dispatched
- [ ] then done: `[]`, undone: `[]`, state: `emptyState + mutationA, mutationB`

**Comment by shurth** [comment]
Not to be "that guy", but were you still thinking about implementing this @andrewbeng89? I was about to roll my own undo/redo plugin and ran into yours, but I'd need 'reset' capabilities so people couldn't undo the initial bootstrapping of the store.

**Comment by andrewbeng89** [comment]
Hi @shurth thanks for you message. This feature is definitely on the roadmap for a future release. There are some _minor_ complexities regarding how this feature will play well with actions/side-effects. Would you be interested to contribute to the development of this feature? We do need help with creating comprehensive test scenarios for this feature.
