### ISSUE TITLE
Persistent Storage / Access the done / undone stack

### ISSUE THREAD

**Issue by billyschonenberg** [factorial-io/undo-redo-vuex#45]
I have been using this plugin for some time, thanks!

I am using it in some hybrid app I'm building. What would be great if can somehow persist the whole undo/redo stack to local storage so the undo functionality keeps working between reloads.

Is this feasible? Or do I need to try another way?

Thanks,
Billy

**Comment by billyschonenberg** [comment]
Any comments / thoughts ?

**Comment by andrewbeng89** [comment]
Hi @billyschonenberg thank you for the feedback and comment about accessing the done/undone stacks. Also, apologies on only just responding to your query now.

Regarding creating an interface to access the stacks, this should be do-able and a useful feature enhancement. I would however recommend that implementing persistence in local storage be done within the scope of your application. This would allow greater flexibility within the app, while keeping the scope of this plugin streamlined.

Does this approach sound reasonable?

**Comment by billyschonenberg** [comment]
Thanks for your response @andrewbeng89. No problem about the reaction time!

Your approach is what I have in mind. I already made the local storage portion of the implementation, since I agree it's outside the scope of the project. So I'll just keep watching this project to see when/if the stacks are accessible. 

Thanks again,
Billy

**Comment by andrewbeng89** [comment]
Hi @billyschonenberg this feature is now available in the [latest 1.4.0 release](https://github.com/factorial-io/undo-redo-vuex/releases/tag/v1.4.0). Please have a go and let me know if there's anything which doesn't work as expected. 🙂

**Comment by billyschonenberg** [comment]
Thanks for your work! I'll try it out and report back here if anything is amiss. 👍
