### ISSUE TITLE
How to call the API getConfig/setConfig/pipActions？

### ISSUE THREAD

**Issue by devilwjp** [factorial-io/undo-redo-vuex#6]
How to call the API **getConfig**, **setConfig**, **pipActions**？

Following the API documentation，

store/plugins/undoRedo:pipeActions(actions)
store/plugins/undoRedo:getConfig(namespace) ⇒ Object
store/plugins/undoRedo:setConfig(namespace, config)

**Comment by mlnmln** [comment]
hi @devilwjp 

sorry for not getting back earlier, we recently moved the repository and missed a couple of notifications.

**Comment by andrewbeng89** [comment]
@devilwjp thank you for your questions concerning the documentation, and apologies again for the delay in getting back to you. 

The current implementation does not expose these functions as part of the exposed API in undo-redo plugin. I realise the current format of the docs is confusing, so I have just updated the docs to [separate the API doc and internal reference](https://github.com/factorial-io/undo-redo-vuex/commit/78396bb0410770c058f30137bb087cc62989d10c).

Please let me know if you do have a use-case for these internal functions to be exposed in the API.
