### ISSUE TITLE
Is it possible to clear undo / redo stack?

### ISSUE THREAD

**Issue by Sueloo** [factorial-io/undo-redo-vuex#7]
Hi,

Thanks for a great plugin! Is it possible to clear the undo / redo stack?

**Comment by mlnmln** [comment]
hi @Sueloo ,

sorry for not getting back earlier, we recently moved the repository and missed a couple of notifications.

**Comment by andrewbeng89** [comment]
@Sueloo thanks for your question 👍and apologies for the late reply. At the moment, this feature is not  available, but should be relatively straightforward to implement.

To get started, could you please confirm whether the criteria for this feature:

- [ ] The `clear` function will be triggered by a noop action called `[optional-namespace/]clear`
- [ ] If there are mutations remaining in the `done` stack, `clear` will undo these mutations (without adding them to the `undone` stack), and all necessary `undoCallbacks` will be called
- [ ] If there are mutations remaining in the `undone` stack, `clear` will set `undone` to an empty stack

**Comment by ma7moudat** [comment]
Hey @andrewbeng89 !
I have a similar use case and an implementation of your specification would be just what I need. Is there a plan to include this in upcoming releases?

**Comment by andrewbeng89** [comment]
Hi @ma7moudat thanks for the feedback on this enhancement to the plugin. I will be creating some test specs for the feature shortly. 

One thing I'd like to clarify about the new feature is the difference between `clear` and `reset` (also yet to be implemented):

- `clear` implies that the state of the store will be _reinitialised_ to its original state, i.e. the state when no mutations had been applied
- `reset` implies that the state of the store will _remain the same at this point_, but undo/redo stacks are emptied, i.e. the subsequent `undo` after the next mutation will return the state of the store to the state when `reset` was called

**Comment by ma7moudat** [comment]
wow! thanks a lot for the quick response and implementation @andrewbeng89  ❤️ 
and you're right, `clear` and `reset` are both needed... in my case `reset` would be more relevant, since I'm working on forms with undo/redo functionality and the user should be able to `reset` the form to repopulate the original values without emptying the state (which `clear` does from your description)

**Comment by andrewbeng89** [comment]
Thanks @ma7moudat! The next steps would be to work on some tests for `reset`, followed by implementation ;)

**Comment by andrewbeng89** [comment]
@ma7moudat the `clear` feature is now available in `v1.2.0`. Could you please try this out? I have also created #13 to prepare the `reset` feature.
