### ISSUE TITLE
Docs setup problem

### ISSUE THREAD

**Issue by gorkamolero** [factorial-io/undo-redo-vuex#8]
Hey guys,

After a day of tinkering, I found out some stuff that wasn't in the docs, but is apparently needed to make the plugin work. Most important, the original emptyState function

I've experimented with providing an initial state, as used to be convention with Redux. This makes it easy to automate reverting the state back to square one. Something like:

````

const initState = {
  items: [...],
  status: {...},
}

const state = initState

const mutations = {
  emptyState: (state) => {
    Object.entries(initState).map(([key, value]) => { state[key] = value })
  },
  ...otherMutations
}

export default {
  namespaced: true,
  mutations: scaffoldMutations(mutations)
}
````

Without this function or some version of it, the plugin doesn't work. Yet it's not in the docs.

Are you open to other people contributing to the project?

**Comment by andrewbeng89** [comment]
Hi @gorkamolero, you are absolutely right about the step on the `emptyState` mutation. I would be happy to accept a PR on the docs for this!
