### ISSUE TITLE
Can you provide a simpler demo?

### ISSUE THREAD

**Issue by starql** [factorial-io/undo-redo-vuex#9]
Thank you for providing this plugin!
This plug-in provides the functions I need, but domo's use method makes me confused. Forgive me for being a novice, but could you introduce a more simple and understandable demo?
I'm not sure how do you get canUndo? I did not get the correct result by trying to use undoButtonEnabled

**Comment by andrewbeng89** [comment]
Hi @starql thanks for using this plugin and your feedback regarding the documentation. (I do agree, it can be very much improved 😉)

I hope these quick pointers will be helpful in the meantime while we brush up the documentation:

- There is a demo Vue.js app project in the `tests/vue-undo-redo-demo` directory. 
- The _actual_ vuex store logic source code used in the demo app is in the `tests/store` directory, as the unit tests also run against this code.
- Your gotos for examples using the plugin to scaffold undo/redo functionality are:
  * (A.)`store-non-namespaced/index.ts`: a basic (state, getters, actions, mutations) vuex store which does _not_ use [vuex modules](https://vuex.vuejs.org/guide/modules.html)
  * (B.)`store/modules/list.ts`: an example of a vuex module with undo/redo wrapped into the `list` module
- The `scaffoldStore` function from the plugin "prepares"/mixes-in the necessary features required for the plugin to work (without any manually writing the code in your own store/module):
  * `canUndo` and `canRedo` state props are added to the store/module: accessible via `state.canUndo` in (A.) or `state.list.canUndo` for modules i.e. (B.)
  * The `undo` and `redo` actions are injected into the vuex actions (you should not implement these actions in your own store/module)
  * The `updateCanUndoRedo` mutation is injected to the vuex mutations (you should not implement this mutation either)

This should get you up to speed with creating a vuex store with undo/redo capabilities, including the `canUndo` and `canRedo` state props. Please let me know if you need further clarification.

**Comment by mlnmln** [comment]
@kgierke 

- [ ] move demo folder out of tests
- [ ] make simplest possible use case 
- [ ] clean test/demo folder
- [ ] embed into vuepress documentation
